name: Go

on:
  push:
#    branches: [ main ]
    tags:
      - v*
#  pull_request:
#    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.step_upload_url.outputs.upload_url }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
        go build -v ./magic.go
        7z a -r magic-test_linux-x64.7z magic

    - name: Create Release
      id: create_release
      uses: actions/create-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: magic-test ${{ github.ref }}
        draft: false
        prerelease: false
#
    - name: Upload Release
      id: upload-release-asset
      uses: actions/upload-release-asset@main
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./magic-test_linux-x64.7z
        asset_name: magic-test_linux-x64.7z
        asset_content_type: application/x-7z-compressed

  buildMac:
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build
        run: |
           go build -v ./magic.go
           7z a -r magic-test_Macos-x64.7z magic
      - name: Upload Release
        id: upload-release-asset
        uses: actions/upload-release-asset@main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ needs.build.outputs.upload_url }}
          asset_path: ./magic-test_Macos-x64.7z
          asset_name: magic-test_Macos-x64.7z
          asset_content_type: application/x-7z-compressed