name: Go

on:
  push:
    branches: [ main ]
    tags:
      - v*
#      - v1.*
#      - v1.1.*
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./magic.go

#    - name: Test
#      run: go test -v ./...
